/// Salesperson dimension. One row per employee with title, email (UPN), and display name. Used to slice Sales by who made the sale.
table Salesperson
	lineageTag: cbc19621-1fb7-4f31-b5cb-370bc3cedd77
	sourceLineageTag: 7d2bb797-a22f-4f92-93c2-336cc56df79c

	/// Surrogate employee key joining Salesperson to Sales. Hidden.
	column EmployeeKey
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: c2b3b0ea-3239-4997-a1aa-2ca38e9ead5b
		sourceLineageTag: 591f68d7-bfad-4d7f-8842-0cb8498d0495
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = User

	/// Business employee ID. Used to join Salesperson to Targets via EmployeeID. Hidden.
	column EmployeeID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fceedb66-c41b-4784-ad45-f1aa73e91698
		sourceLineageTag: 4bf7f41f-a528-41f8-9199-f11b756e2c19
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = User

	/// Job title (e.g. Sales Representative).
	column Title
		dataType: string
		lineageTag: ff060f67-3bd0-40d4-8901-3b48fc2af0ef
		sourceLineageTag: 1466b05f-5751-4cac-b629-a33b5548417d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = User

	/// User principal name (work email). Hidden; useful for row-level security mapping.
	column UPN
		dataType: string
		isHidden
		lineageTag: a599a387-90bf-46b7-8ac2-404c515a1501
		sourceLineageTag: 89a9123a-ff31-473a-8f27-f8e396f7ed76
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: UPN

		annotation SummarizationSetBy = User

	/// Salesperson display name shown in visuals.
	column Salesperson
		dataType: string
		lineageTag: 8f88ca97-c2a7-40de-a3e2-1fa6c82b5fc7
		sourceLineageTag: 8459bc64-a465-4094-ac97-0202fdb87d70
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = User

	partition Salesperson = m
		mode: import
		source =
				let
				    Source = Table.FromRecords({
				        [EmployeeKey = 1, EmployeeID = 272, Title = "Sales Representative", UPN = "michael9@adventure-works.com", Salesperson = "Michael Blythe"],
				        [EmployeeKey = 2, EmployeeID = 281, Title = "Sales Representative", UPN = "linda3@adventure-works.com", Salesperson = "Linda Mitchell"],
				        [EmployeeKey = 3, EmployeeID = 282, Title = "Sales Representative", UPN = "jillian0@adventure-works.com", Salesperson = "Jillian Carson"],
				        [EmployeeKey = 4, EmployeeID = 283, Title = "Sales Representative", UPN = "garret1@adventure-works.com", Salesperson = "Garrett Vargas"],
				        [EmployeeKey = 5, EmployeeID = 284, Title = "Sales Representative", UPN = "tsvi0@adventure-works.com", Salesperson = "Tsvi Reiter"],
				        [EmployeeKey = 6, EmployeeID = 285, Title = "Sales Representative", UPN = "pamela0@adventure-works.com", Salesperson = "Pamela Ansman-Wolfe"],
				        [EmployeeKey = 7, EmployeeID = 286, Title = "Sales Representative", UPN = "shu0@adventure-works.com", Salesperson = "Shu Ito"],
				        [EmployeeKey = 8, EmployeeID = 290, Title = "Sales Representative", UPN = "jose1@adventure-works.com", Salesperson = "Jose Saraiva"]
				    }, type table [EmployeeKey = Int64.Type, EmployeeID = Int64.Type, Title = Text.Type, UPN = Text.Type, Salesperson = Text.Type])
				in
				    Source

