/// Sales fact table. One row per order line with quantity, unit price, line-level sales amount, and cost. Hosts the core sales, profit, and time-intelligence measures used across the report.
table Sales
	lineageTag: d011e21c-3913-493a-b6fd-5022a2c14e7d
	sourceLineageTag: c90c54c3-ecc7-4006-acae-213e629b2b9e

	/// Gross profit = Sales Amount minus Cost. DAX: subtracts the total of Sales[Cost] from the total of Sales[Sales Amount] in the current filter context (selected dates, regions, products, etc.).
	measure Profit = SUM(Sales[Sales Amount]) - SUM(Sales[Cost])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f5b89451-737b-47aa-808c-45d229f927cc
		sourceLineageTag: e9392e16-8287-4a63-8f98-14ddbc88ec6d
		dataCategory: Uncategorized

	/// Profit as a percentage of sales. DAX: DIVIDE([Profit], SUM(Sales[Sales Amount])). DIVIDE is used instead of '/' so a zero-sales context returns blank rather than a divide-by-zero error.
	measure 'Profit Margin' = DIVIDE([Profit], SUM(Sales[Sales Amount]))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 2365c808-8b7d-46b6-b24a-8a13cbba8746
		sourceLineageTag: 6dcf0ce0-a21f-454e-8857-7bf5e2b7b031
		dataCategory: Uncategorized

	/// Mean selling price per unit across the rows in scope. DAX: AVERAGE over Sales[Unit Price] - a simple arithmetic mean of the per-line unit prices, not weighted by quantity.
	measure 'Average Price' = AVERAGE(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 9bcfa08f-1bf3-49d8-b35d-5dad67a2f666
		sourceLineageTag: 9ca76f2a-b132-4cb0-813c-f4e65d5f9c71
		dataCategory: Uncategorized

	/// Middle selling price - the value where half of lines are above and half below. DAX: MEDIAN over Sales[Unit Price]. Less skewed by outliers than Average Price.
	measure 'Median Price' = MEDIAN(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: d68aa176-2c6e-4404-a0a4-a31d13a4f388
		sourceLineageTag: 22c94527-a543-4638-8cf7-fb934808620e
		dataCategory: Uncategorized

	/// Lowest unit price observed in the current filter context. DAX: MIN over Sales[Unit Price].
	measure 'Min Price' = MIN(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: a8fca671-da86-48a7-842f-176b7c4d9fdb
		sourceLineageTag: 94d285a5-58ae-40fb-98dd-29b64a058507
		dataCategory: Uncategorized

	/// Highest unit price observed in the current filter context. DAX: MAX over Sales[Unit Price].
	measure 'Max Price' = MAX(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: d48c8467-4a85-4ef6-afe1-249de8c38e5c
		sourceLineageTag: 793f0df1-015b-4908-b5bd-aefbd1dfdb62
		dataCategory: Uncategorized

	/// Count of distinct sales orders. DAX: DISTINCTCOUNT of Sales[SalesOrderNumber] - because an order can contain multiple line rows, distinct-count collapses them so one order is counted once.
	measure Orders = DISTINCTCOUNT(Sales[SalesOrderNumber])
		formatString: 0
		displayFolder: Counts
		lineageTag: 4fb79728-a93b-4fa8-b114-d53b49b59898
		sourceLineageTag: 57f38fd6-cf9a-4d06-a7ee-1a306043c61b
		dataCategory: Uncategorized

	/// Total number of order lines (rows in Sales) in the current filter context. DAX: COUNTROWS(Sales). Differs from Orders because a single order can have many lines.
	measure 'Order Lines' = COUNTROWS(Sales)
		formatString: 0
		displayFolder: Counts
		lineageTag: 4d5dff7c-93b6-4231-9131-25e4e346ef46
		sourceLineageTag: da03adc1-acfb-4d73-9aaa-b5e373c5e88f
		dataCategory: Uncategorized

	/// Share of total sales contributed by the current selection, vs. all regions combined. DAX: DIVIDE(SUM(Sales[Sales Amount]), CALCULATE(SUM(Sales[Sales Amount]), ALL(Region))). The ALL(Region) inside CALCULATE removes any filter on Region for the denominator, so the result is always 'this selection / world total'.
	measure 'Sales % All Regions' = DIVIDE(SUM(Sales[Sales Amount]), CALCULATE(SUM(Sales[Sales Amount]), ALL(Region)))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: 8ffba007-60e8-44ea-9c67-d4ab7213dce5
		sourceLineageTag: 008e9ca5-2758-43de-9595-76282e69f31d
		dataCategory: Uncategorized

	/// Share of sales within the current country. DAX: ALLEXCEPT(Region, Region[Group], Region[Country]) keeps Group and Country filters in the denominator but removes any Region-level filter, so the result is 'this region / its country total'.
	measure 'Sales % Country' = DIVIDE(SUM(Sales[Sales Amount]), CALCULATE(SUM(Sales[Sales Amount]), ALLEXCEPT(Region, Region[Group], Region[Country])))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: f19a72b2-708f-41c6-bb5c-7eb6d1913698
		sourceLineageTag: 954e603d-5c04-4a90-ad4c-8f34b04ea323
		dataCategory: Uncategorized

	/// Share of sales within the current regional Group. DAX: ALLEXCEPT(Region, Region[Group]) keeps the Group filter but removes Country/Region filters in the denominator, so the result is 'this region / its group total'.
	measure 'Sales % Group' = DIVIDE(SUM(Sales[Sales Amount]), CALCULATE(SUM(Sales[Sales Amount]), ALLEXCEPT(Region, Region[Group])))
		displayFolder: Ratios
		lineageTag: a0178da3-679c-4e41-8fc7-87132d7b59f0
		sourceLineageTag: 565a0642-ff70-4055-95e3-f5233d204ae8
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Cumulative sales from the start of the calendar year through the dates in context. DAX: TOTALYTD wraps SUM(Sales[Sales Amount]) and uses 'Date'[Date] as the timeline. Requires the Date table to be marked as a date table and joined to Sales on OrderDate.
	measure 'Sales YTD' = TOTALYTD(SUM(Sales[Sales Amount]), 'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Time Intelligence
		lineageTag: ccc1d7bc-af20-49c7-9e9b-ac44d6c367f0
		sourceLineageTag: a9440108-f6a0-4e23-b6c9-9fa7662ff79b
		dataCategory: Uncategorized

	/// Year-over-year growth as a percentage. DAX: stores prior-year sales in a VAR using SAMEPERIODLASTYEAR (shifts the date filter back 12 months), then computes (current - prior) / prior using DIVIDE so the result is blank when there is no prior-year value.
	measure 'Sales YoY Growth' =
			VAR SalesPriorYear = CALCULATE(SUM(Sales[Sales Amount]), SAMEPERIODLASTYEAR('Date'[Date]))
			RETURN DIVIDE(SUM(Sales[Sales Amount]) - SalesPriorYear, SalesPriorYear)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time Intelligence
		lineageTag: 01e5408a-0d93-4ce4-868b-e7ac0af695d2
		sourceLineageTag: 5e215bb9-dc07-4caa-a171-431cb225e29a
		dataCategory: Uncategorized

	/// Sales normalized by US state population. DAX: DIVIDE(SUM(Sales[Sales Amount]), SUM('US Population'[Population])) - useful for comparing markets of different sizes (e.g. small state vs. large state).
	measure 'Sales per Capita' = DIVIDE(SUM(Sales[Sales Amount]), SUM('US Population'[Population]))
		formatString: \$#,0.0000;(\$#,0.0000);\$#,0.0000
		lineageTag: db973cbe-3ea9-4cf7-8620-fc10c469846a

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Sales order identifier (e.g. SO-0001). Used by the Orders measure via DISTINCTCOUNT to count unique orders. Hidden.
	column SalesOrderNumber
		dataType: string
		isHidden
		lineageTag: 18a24817-e9f3-4a20-9791-ad94fb212fc1
		sourceLineageTag: f7a951a1-052d-44bb-911c-0f487977d8e6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = User

	/// Date the order was placed. Joined to Date[Date] to enable time-intelligence calculations. Hidden.
	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 7c0d9970-6bc3-4c26-b38f-0301be6c12ed
		sourceLineageTag: f09e25ae-d1b9-4233-80a0-f947efe49834
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = User

	/// Foreign key to Product[ProductKey]. Hidden.
	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dda7131c-3acc-495b-b668-9ca532ad26a6
		sourceLineageTag: 322e241e-6244-4cd7-bb79-bf30ad967c85
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = User

	/// Foreign key to Reseller[ResellerKey]. Hidden.
	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7b4c97b4-752d-4cac-8282-704e0781130c
		sourceLineageTag: fa69a045-873a-49b5-847a-2eda5565fab7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = User

	/// Foreign key to Salesperson[EmployeeKey]. Hidden.
	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 147f7056-135a-423d-8fc3-0dd44c7d8f10
		sourceLineageTag: 84ab0fd3-0c83-4456-a495-f0e3817be1b3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = User

	/// Foreign key to Region[SalesTerritoryKey]. Hidden.
	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 03bf3b2e-8f32-4d46-8806-34619ef3cc26
		sourceLineageTag: e2190568-d580-4d50-abaf-e366040afd52
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = User

	/// Number of units sold on the order line. Aggregates by SUM.
	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: 168cbd6e-ec87-4ed9-a111-ae44aa6dc200
		sourceLineageTag: 1f8ac87e-c2b3-4d8f-bf03-f927b297974e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

	/// Selling price per unit. Hidden because it's a per-row attribute; use the Average/Median/Min/Max Price measures for aggregation.
	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f78ff5ec-9377-405a-b8a4-62fd9df32f74
		sourceLineageTag: 914c5056-0675-4279-90b9-9b47f4096186
		dataCategory: Uncategorized
		summarizeBy: average
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

	/// Line-level sales amount (Quantity x Unit Price). The base column summed by Profit, Sales YTD, and the Sales % measures.
	column 'Sales Amount'
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a655ad3f-e507-41ee-906b-5bd46e112411
		sourceLineageTag: 4465de7d-4f58-462b-8ddb-6207fcce0d92
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = User

	/// Line-level cost based on Product[Standard Cost]. Subtracted from Sales Amount in the Profit measure.
	column Cost
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f6c2d3b3-e972-4b29-9109-4684dfbe900b
		sourceLineageTag: 4891cf60-2811-4a99-9d25-63cb318cbb38
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = User

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRecords({
				        [SalesOrderNumber = "SO-0001", OrderDate = #datetime(2022, 1, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 2, EmployeeKey = 1, SalesTerritoryKey = 2, Quantity = 2, #"Unit Price" = 3578.27, Sales = 7156.54, Cost = 4342.58],
				        [SalesOrderNumber = "SO-0002", OrderDate = #datetime(2022, 1, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 1, EmployeeKey = 2, SalesTerritoryKey = 3, Quantity = 3, #"Unit Price" = 3190.00, Sales = 9570.00, Cost = 5736.45],
				        [SalesOrderNumber = "SO-0003", OrderDate = #datetime(2022, 1, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 3, EmployeeKey = 4, SalesTerritoryKey = 1, Quantity = 1, #"Unit Price" = 3598.00, Sales = 3598.00, Cost = 2146.96],
				        [SalesOrderNumber = "SO-0004", OrderDate = #datetime(2022, 4, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 4, #"Unit Price" = 3578.27, Sales = 14313.08, Cost = 8685.16],
				        [SalesOrderNumber = "SO-0005", OrderDate = #datetime(2022, 4, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 2, #"Unit Price" = 3190.00, Sales = 6380.00, Cost = 3824.30],
				        [SalesOrderNumber = "SO-0006", OrderDate = #datetime(2022, 4, 1, 0, 0, 0), ProductKey = 2, ResellerKey = 7, EmployeeKey = 6, SalesTerritoryKey = 6, Quantity = 20, #"Unit Price" = 34.99, Sales = 699.80, Cost = 261.80],
				        [SalesOrderNumber = "SO-0007", OrderDate = #datetime(2022, 7, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 6, EmployeeKey = 7, SalesTerritoryKey = 7, Quantity = 5, #"Unit Price" = 3578.27, Sales = 17891.35, Cost = 10856.45],
				        [SalesOrderNumber = "SO-0008", OrderDate = #datetime(2022, 7, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 8, EmployeeKey = 8, SalesTerritoryKey = 8, Quantity = 3, #"Unit Price" = 3598.00, Sales = 10794.00, Cost = 6440.88],
				        [SalesOrderNumber = "SO-0009", OrderDate = #datetime(2022, 7, 1, 0, 0, 0), ProductKey = 1, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 100, #"Unit Price" = 8.99, Sales = 899.00, Cost = 692.20],
				        [SalesOrderNumber = "SO-0010", OrderDate = #datetime(2022, 10, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 1, EmployeeKey = 2, SalesTerritoryKey = 3, Quantity = 4, #"Unit Price" = 3190.00, Sales = 12760.00, Cost = 7648.60],
				        [SalesOrderNumber = "SO-0011", OrderDate = #datetime(2022, 10, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 3, #"Unit Price" = 3578.27, Sales = 10734.81, Cost = 6513.87],
				        [SalesOrderNumber = "SO-0012", OrderDate = #datetime(2022, 10, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 2, EmployeeKey = 1, SalesTerritoryKey = 2, Quantity = 2, #"Unit Price" = 3598.00, Sales = 7196.00, Cost = 4293.92],
				        [SalesOrderNumber = "SO-0013", OrderDate = #datetime(2022, 10, 1, 0, 0, 0), ProductKey = 3, ResellerKey = 7, EmployeeKey = 6, SalesTerritoryKey = 6, Quantity = 50, #"Unit Price" = 9.50, Sales = 475.00, Cost = 170.00],
				        [SalesOrderNumber = "SO-0014", OrderDate = #datetime(2023, 1, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 6, #"Unit Price" = 3578.27, Sales = 21469.62, Cost = 13027.74],
				        [SalesOrderNumber = "SO-0015", OrderDate = #datetime(2023, 1, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 3, EmployeeKey = 4, SalesTerritoryKey = 1, Quantity = 4, #"Unit Price" = 3190.00, Sales = 12760.00, Cost = 7648.60],
				        [SalesOrderNumber = "SO-0016", OrderDate = #datetime(2023, 1, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 6, EmployeeKey = 7, SalesTerritoryKey = 7, Quantity = 5, #"Unit Price" = 3598.00, Sales = 17990.00, Cost = 10734.80],
				        [SalesOrderNumber = "SO-0017", OrderDate = #datetime(2023, 1, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 3, #"Unit Price" = 3578.27, Sales = 10734.81, Cost = 6513.87],
				        [SalesOrderNumber = "SO-0018", OrderDate = #datetime(2023, 4, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 2, EmployeeKey = 1, SalesTerritoryKey = 2, Quantity = 5, #"Unit Price" = 3190.00, Sales = 15950.00, Cost = 9560.75],
				        [SalesOrderNumber = "SO-0019", OrderDate = #datetime(2023, 4, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 4, #"Unit Price" = 3598.00, Sales = 14392.00, Cost = 8587.84],
				        [SalesOrderNumber = "SO-0020", OrderDate = #datetime(2023, 4, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 1, EmployeeKey = 2, SalesTerritoryKey = 3, Quantity = 7, #"Unit Price" = 3578.27, Sales = 25047.89, Cost = 15199.03],
				        [SalesOrderNumber = "SO-0021", OrderDate = #datetime(2023, 4, 1, 0, 0, 0), ProductKey = 2, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 30, #"Unit Price" = 34.99, Sales = 1049.70, Cost = 392.70],
				        [SalesOrderNumber = "SO-0022", OrderDate = #datetime(2023, 7, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 3, EmployeeKey = 4, SalesTerritoryKey = 1, Quantity = 6, #"Unit Price" = 3190.00, Sales = 19140.00, Cost = 11472.90],
				        [SalesOrderNumber = "SO-0023", OrderDate = #datetime(2023, 7, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 7, EmployeeKey = 6, SalesTerritoryKey = 6, Quantity = 4, #"Unit Price" = 3578.27, Sales = 14313.08, Cost = 8685.16],
				        [SalesOrderNumber = "SO-0024", OrderDate = #datetime(2023, 7, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 2, EmployeeKey = 1, SalesTerritoryKey = 2, Quantity = 3, #"Unit Price" = 3598.00, Sales = 10794.00, Cost = 6440.88],
				        [SalesOrderNumber = "SO-0025", OrderDate = #datetime(2023, 7, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 4, #"Unit Price" = 3190.00, Sales = 12760.00, Cost = 7648.60],
				        [SalesOrderNumber = "SO-0026", OrderDate = #datetime(2023, 7, 1, 0, 0, 0), ProductKey = 1, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 200, #"Unit Price" = 8.99, Sales = 1798.00, Cost = 1384.40],
				        [SalesOrderNumber = "SO-0027", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 8, EmployeeKey = 8, SalesTerritoryKey = 8, Quantity = 5, #"Unit Price" = 3578.27, Sales = 17891.35, Cost = 10856.45],
				        [SalesOrderNumber = "SO-0028", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 6, ResellerKey = 6, EmployeeKey = 7, SalesTerritoryKey = 7, Quantity = 6, #"Unit Price" = 3598.00, Sales = 21588.00, Cost = 12881.76],
				        [SalesOrderNumber = "SO-0029", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 2, EmployeeKey = 1, SalesTerritoryKey = 2, Quantity = 4, #"Unit Price" = 3190.00, Sales = 12760.00, Cost = 7648.60],
				        [SalesOrderNumber = "SO-0030", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 3, ResellerKey = 5, EmployeeKey = 5, SalesTerritoryKey = 5, Quantity = 100, #"Unit Price" = 9.50, Sales = 950.00, Cost = 340.00],
				        [SalesOrderNumber = "SO-0031", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 4, ResellerKey = 4, EmployeeKey = 3, SalesTerritoryKey = 4, Quantity = 8, #"Unit Price" = 3578.27, Sales = 28626.16, Cost = 17370.32],
				        [SalesOrderNumber = "SO-0032", OrderDate = #datetime(2023, 10, 1, 0, 0, 0), ProductKey = 5, ResellerKey = 3, EmployeeKey = 4, SalesTerritoryKey = 1, Quantity = 5, #"Unit Price" = 3190.00, Sales = 15950.00, Cost = 9560.75]
				    }, type table [SalesOrderNumber = Text.Type, OrderDate = DateTime.Type, ProductKey = Int64.Type, ResellerKey = Int64.Type, EmployeeKey = Int64.Type, SalesTerritoryKey = Int64.Type, Quantity = Int64.Type, #"Unit Price" = Decimal.Type, Sales = Decimal.Type, Cost = Decimal.Type])
				in
				    Source

