# © 2026 Martín Viera. Todos los derechos reservados.
# Software propietario. Ver LICENSE — prohibida su redistribución.
"""
MV Data Governance · Todo lo que hay que preguntarle al cliente, por área.

Para qué
────────
Un relevamiento se hace una vez y mal, o se hace con una lista. La diferencia
la paga el proyecto tres meses después: el dato que nadie preguntó aparece
como un supuesto en el diseño, y el supuesto aparece como un rehacer.

Este es el banco de preguntas. Está partido por **área del pipeline de data
engineering** — las mismas 12 etapas de ``mvdg.pipeline_doc``, no una
taxonomía paralela — porque el objetivo de preguntar es poder construir cada
etapa, y una pregunta que no sirve para ninguna etapa no debería estar acá.

Cada pregunta lleva cuatro cosas, y las cuatro se usan:

  pregunta     qué se pregunta, en criollo. Se lee en voz alta tal cual.
  porque       QUÉ SE ROMPE si no se sabe. Es lo que hace que el que
               responde entienda por qué le están preguntando, y lo que
               permite decidir qué preguntas saltear cuando hay 40 minutos
               de reunión y no dos horas.
  a_quien      el rol que suele tener la respuesta. Preguntarle a la persona
               equivocada no da una respuesta mala: da una respuesta
               inventada, que es peor porque parece buena.
  repreguntas  qué volver a preguntar cuando la respuesta quedó a medias.
               Sin esto, "sí, tenemos un maestro de clientes" se anota como
               si fuera información.

Por qué este archivo es largo
─────────────────────────────
Es una tabla de datos, no lógica: 36 preguntas por 3 idiomas. Partirlo en
tres archivos por criterio de largo dejaría el banco repartido sin que
ninguna parte se entienda sola. La lógica que lo consume vive en
``mvdg.interview``, que sí es corto.
"""
from __future__ import annotations


def _tr(es: str, en: str, pt: str) -> dict:
    return {"es": es, "en": en, "pt": pt}


def _q(qid: str, area: str, pregunta: tuple, porque: tuple, a_quien: tuple,
       *repreguntas: tuple) -> dict:
    return {
        "id": qid, "area": area,
        "pregunta": _tr(*pregunta), "porque": _tr(*porque),
        "a_quien": _tr(*a_quien),
        "repreguntas": [_tr(*r) for r in repreguntas],
    }


# ---------------------------------------------------------------------------
# El banco. El orden es el del pipeline: así una reunión larga se recorre de
# principio a fin y una corta se corta por donde se llegó, sin saltear el
# medio.
# ---------------------------------------------------------------------------
PREGUNTAS: list[dict] = [
    # ------------------------------------------------------------- 1 ingesta
    _q("ING-01", "ingesta",
       ("¿De qué sistemas salen hoy los datos que vamos a gobernar, y quién da el acceso?",
        "Which systems do the data we are going to govern come from today, and who grants access?",
        "De quais sistemas saem hoje os dados que vamos governar, e quem dá o acesso?"),
       ("Sin esto no se puede ni empezar: se descubre el tercer sistema cuando el diseño ya está cerrado.",
        "Without this you cannot even start: the third system turns up when the design is already closed.",
        "Sem isso não dá nem para começar: o terceiro sistema aparece quando o desenho já está fechado."),
       ("Responsable de TI / arquitectura", "IT / architecture lead", "Responsável de TI / arquitetura"),
       ("¿Hay algún dato que hoy viva SOLO en una planilla de alguien?",
        "Is there any data that today lives ONLY in someone's spreadsheet?",
        "Há algum dado que hoje viva SÓ na planilha de alguém?"),
       ("¿El acceso lo da una persona o hay un circuito formal? ¿Cuánto tarda?",
        "Is access granted by one person or is there a formal process? How long does it take?",
        "O acesso é dado por uma pessoa ou há um circuito formal? Quanto demora?")),
    _q("ING-02", "ingesta",
       ("¿Cada cuánto se actualiza cada fuente, y a qué hora?",
        "How often is each source updated, and at what time?",
        "Com que frequência cada fonte é atualizada, e a que hora?"),
       ("Define si el pipeline corre de noche, cada hora o en vivo. Cambiarlo después es rehacerlo.",
        "It decides whether the pipeline runs nightly, hourly or live. Changing it later means rebuilding it.",
        "Define se o pipeline roda de noite, de hora em hora ou ao vivo. Mudar depois é refazer."),
       ("Operaciones / DBA", "Operations / DBA", "Operações / DBA"),
       ("¿Qué pasa si un día no corre? ¿Alguien se entera?",
        "What happens if one day it does not run? Does anyone find out?",
        "O que acontece se um dia não rodar? Alguém fica sabendo?")),
    _q("ING-03", "ingesta",
       ("¿Qué volumen tiene cada fuente: filas, tamaño, y cuánto crece por mes?",
        "What volume does each source have: rows, size, and how much does it grow per month?",
        "Que volume tem cada fonte: linhas, tamanho, e quanto cresce por mês?"),
       ("Un diseño que anda con 100.000 filas y muere con 40 millones es un diseño que hay que tirar.",
        "A design that works with 100,000 rows and dies at 40 million is a design you have to throw away.",
        "Um desenho que funciona com 100.000 linhas e morre com 40 milhões é um desenho para jogar fora."),
       ("DBA / dueño del sistema", "DBA / system owner", "DBA / dono do sistema"),
       ("¿Hay historia vieja que también hay que traer, o se arranca de una fecha?",
        "Is there old history to bring in too, or do we start from a date?",
        "Há histórico antigo para trazer também, ou começamos de uma data?")),
    # ----------------------------------------------------------- 2 perfilado
    _q("PER-01", "perfilado",
       ("¿Qué campos saben que vienen sucios, incompletos o cargados a mano?",
        "Which fields do you know come in dirty, incomplete or typed by hand?",
        "Quais campos vocês sabem que vêm sujos, incompletos ou digitados à mão?"),
       ("La gente del negocio ya sabe dónde está la basura. Descubrirlo perfilando cuesta dos semanas más.",
        "Business people already know where the garbage is. Finding it by profiling costs two more weeks.",
        "O pessoal do negócio já sabe onde está o lixo. Descobrir perfilando custa duas semanas a mais."),
       ("Usuario clave del área", "Key business user", "Usuário-chave da área"),
       ("¿Ese campo es obligatorio en el sistema o se puede dejar vacío?",
        "Is that field mandatory in the system or can it be left empty?",
        "Esse campo é obrigatório no sistema ou pode ficar vazio?")),
    _q("PER-02", "perfilado",
       ("¿Hay campos que se usan para algo distinto de lo que dice su nombre?",
        "Are there fields used for something other than what their name says?",
        "Há campos usados para algo diferente do que o nome diz?"),
       ("El campo 'observaciones' que en realidad guarda el número de contrato rompe cualquier regla automática.",
        "The 'notes' field that actually stores the contract number breaks any automatic rule.",
        "O campo 'observações' que na verdade guarda o número do contrato quebra qualquer regra automática."),
       ("Usuario clave del área", "Key business user", "Usuário-chave da área"),
       ("¿Desde cuándo se usa así? ¿Los registros viejos siguen la misma lógica?",
        "Since when is it used that way? Do old records follow the same logic?",
        "Desde quando é usado assim? Os registros antigos seguem a mesma lógica?")),
    _q("PER-03", "perfilado",
       ("¿Qué campos tienen datos personales: nombre, documento, mail, teléfono, salud?",
        "Which fields hold personal data: name, ID, email, phone, health?",
        "Quais campos têm dados pessoais: nome, documento, e-mail, telefone, saúde?"),
       ("Decide qué se puede mostrar, a quién, y qué hay que enmascarar antes de que salga a un tablero.",
        "It decides what can be shown, to whom, and what must be masked before it reaches a dashboard.",
        "Decide o que pode ser mostrado, a quem, e o que precisa ser mascarado antes de ir para um painel."),
       ("Legales / compliance / seguridad", "Legal / compliance / security", "Jurídico / compliance / segurança"),
       ("¿Hay alguna norma interna o regulación que aplique (habeas data, GDPR, sectorial)?",
        "Is there an internal policy or regulation that applies (data protection, GDPR, sector rules)?",
        "Há alguma norma interna ou regulação aplicável (proteção de dados, GDPR, setorial)?")),
    # ----------------------------------------------------------- 3 catálogo
    _q("CAT-01", "catalogo",
       ("Por cada dataset: ¿quién es el DUEÑO (decide) y quién el STEWARD (lo cuida día a día)?",
        "For each dataset: who is the OWNER (decides) and who the STEWARD (looks after it daily)?",
        "Para cada dataset: quem é o DONO (decide) e quem o STEWARD (cuida no dia a dia)?"),
       ("Sin nombre y apellido, cada defecto que aparezca no tiene a quién derivarse y queda dando vueltas.",
        "With no name attached, every defect that appears has nobody to route to and just circulates.",
        "Sem nome e sobrenome, cada defeito que aparece não tem para quem ir e fica circulando."),
       ("Gerente del área dueña del dato", "Manager of the owning area", "Gerente da área dona do dado"),
       ("¿Esa persona lo sabe y lo aceptó, o se lo estamos asignando nosotros?",
        "Does that person know and accept it, or are we assigning it ourselves?",
        "Essa pessoa sabe e aceitou, ou estamos atribuindo nós?"),
       ("¿Quién decide si se rechaza una carga con errores: el dueño o TI?",
        "Who decides whether a load with errors is rejected: the owner or IT?",
        "Quem decide se uma carga com erros é rejeitada: o dono ou TI?")),
    _q("CAT-02", "catalogo",
       ("¿Qué pasa hoy cuando alguien necesita un dato que no tiene? ¿A quién le pide?",
        "What happens today when someone needs data they do not have? Who do they ask?",
        "O que acontece hoje quando alguém precisa de um dado que não tem? A quem pede?"),
       ("Muestra si hay un catálogo real o si el catálogo es una persona que atiende pedidos por chat.",
        "It shows whether there is a real catalogue or the catalogue is one person handling requests by chat.",
        "Mostra se há um catálogo real ou se o catálogo é uma pessoa atendendo pedidos por chat."),
       ("Usuarios de negocio y BI", "Business and BI users", "Usuários de negócio e BI"),
       ("¿Cuánto tarda en promedio? ¿Alguna vez se resolvió mandando un Excel por mail?",
        "How long does it take on average? Was it ever solved by emailing an Excel?",
        "Quanto demora em média? Alguma vez foi resolvido mandando um Excel por e-mail?")),
    _q("CAT-03", "catalogo",
       ("¿Existe ya algún catálogo, inventario o herramienta de gobierno (Purview, Collibra, una planilla)?",
        "Is there already a catalogue, inventory or governance tool (Purview, Collibra, a spreadsheet)?",
        "Já existe algum catálogo, inventário ou ferramenta de governança (Purview, Collibra, uma planilha)?"),
       ("Si ya hay algo, hay que integrarse, no competir: dos catálogos es peor que ninguno.",
        "If something exists, integrate with it rather than compete: two catalogues are worse than none.",
        "Se já existe algo, integre em vez de competir: dois catálogos é pior que nenhum."),
       ("Arquitectura de datos", "Data architecture", "Arquitetura de dados"),
       ("¿Está actualizado? ¿Cuándo fue la última vez que alguien lo tocó?",
        "Is it up to date? When did someone last touch it?",
        "Está atualizado? Quando foi a última vez que alguém mexeu nele?")),
    # -------------------------------------------------------- 4 diccionario
    _q("DIC-01", "diccionario",
       ("¿Qué campos significan cosas distintas según el área que los mire?",
        "Which fields mean different things depending on which area looks at them?",
        "Quais campos significam coisas diferentes conforme a área que os olha?"),
       ("Es el origen del 'los números no cierran': dos áreas midiendo distinto y las dos con razón.",
        "It is the root of 'the numbers do not match': two areas measuring differently, both right.",
        "É a origem do 'os números não batem': duas áreas medindo diferente, as duas certas."),
       ("Referentes de cada área", "Area representatives", "Referentes de cada área"),
       ("¿Cuál de las dos definiciones va al tablero? ¿Quién lo decide?",
        "Which of the two definitions goes to the dashboard? Who decides?",
        "Qual das duas definições vai para o painel? Quem decide?")),
    _q("DIC-02", "diccionario",
       ("¿Hay códigos, siglas o estados que solo entiende quien trabaja ahí hace años?",
        "Are there codes, acronyms or statuses only long-time staff understand?",
        "Há códigos, siglas ou status que só quem trabalha lá há anos entende?"),
       ("Ese conocimiento se va con la persona. Documentarlo es la mitad del valor de un glosario.",
        "That knowledge leaves with the person. Documenting it is half the value of a glossary.",
        "Esse conhecimento vai embora com a pessoa. Documentar é metade do valor de um glossário."),
       ("Usuario con más antigüedad", "Longest-tenured user", "Usuário mais antigo"),
       ("¿Está escrito en algún lado o está en la cabeza de alguien?",
        "Is it written down anywhere or is it in someone's head?",
        "Está escrito em algum lugar ou está na cabeça de alguém?")),
    # ------------------------------------------------------------- 5 reglas
    _q("REG-01", "reglas",
       ("¿Qué tiene que cumplir un registro para que ustedes lo consideren válido?",
        "What must a record satisfy for you to consider it valid?",
        "O que um registro precisa cumprir para vocês considerarem válido?"),
       ("Es literalmente el insumo de las reglas de calidad. Sin esto las reglas las inventa el consultor.",
        "It is literally the input for the quality rules. Without it the consultant invents them.",
        "É literalmente o insumo das regras de qualidade. Sem isso o consultor as inventa."),
       ("Usuario clave + control interno", "Key user + internal control", "Usuário-chave + controle interno"),
       ("¿Hay un caso legítimo donde eso NO se cumple? ¿Cómo lo distinguimos de un error?",
        "Is there a legitimate case where that does NOT hold? How do we tell it from an error?",
        "Há um caso legítimo em que isso NÃO se cumpre? Como distinguimos de um erro?")),
    _q("REG-02", "reglas",
       ("Cuando aparece un dato mal, ¿qué hacen hoy: se corrige, se ignora o se rechaza la carga?",
        "When bad data shows up, what do you do today: fix it, ignore it, or reject the load?",
        "Quando aparece um dado errado, o que fazem hoje: corrigem, ignoram ou rejeitam a carga?"),
       ("Define si las reglas van a ser un semáforo o un portón. Son dos productos distintos.",
        "It decides whether the rules are a traffic light or a gate. Those are two different products.",
        "Define se as regras serão um semáforo ou um portão. São dois produtos diferentes."),
       ("Responsable del proceso", "Process owner", "Responsável do processo"),
       ("¿Quién corrige? ¿En el sistema de origen o en el reporte?",
        "Who fixes it? In the source system or in the report?",
        "Quem corrige? No sistema de origem ou no relatório?")),
    _q("REG-03", "reglas",
       ("¿Qué error de datos ya les costó plata, tiempo o un problema con un cliente?",
        "Which data error has already cost you money, time or a problem with a customer?",
        "Qual erro de dados já custou dinheiro, tempo ou um problema com um cliente?"),
       ("Es la regla que hay que escribir primero, y el caso con el que se justifica el proyecto entero.",
        "It is the first rule to write, and the case that justifies the whole project.",
        "É a primeira regra a escrever, e o caso que justifica o projeto inteiro."),
       ("Gerencia del área", "Area management", "Gerência da área"),
       ("¿Cuántas veces pasó? ¿Se puede poner un número a lo que costó?",
        "How many times did it happen? Can you put a number on what it cost?",
        "Quantas vezes aconteceu? Dá para colocar um número no que custou?")),
    # ------------------------------------------------------------- 6 índice
    _q("IDX-01", "indice",
       ("¿Cómo sabrían hoy si la calidad de los datos mejoró o empeoró respecto al mes pasado?",
        "How would you know today whether data quality improved or got worse versus last month?",
        "Como saberiam hoje se a qualidade dos dados melhorou ou piorou em relação ao mês passado?"),
       ("Si no hay forma de saberlo, no hay forma de mostrar que el proyecto sirvió. Es la línea de base.",
        "If there is no way to know, there is no way to show the project worked. It is the baseline.",
        "Se não há como saber, não há como mostrar que o projeto serviu. É a linha de base."),
       ("Sponsor del proyecto", "Project sponsor", "Patrocinador do projeto"),
       ("¿Qué número le mostrarían al directorio para decir que esto funcionó?",
        "What number would you show the board to say this worked?",
        "Que número mostrariam à diretoria para dizer que isso funcionou?")),
    _q("IDX-02", "indice",
       ("¿A quién y cada cuánto habría que avisarle cuando la calidad baja de cierto punto?",
        "Who should be told, and how often, when quality drops below a threshold?",
        "A quem e com que frequência avisar quando a qualidade cai abaixo de um ponto?"),
       ("Una alerta que no llega a nadie es un log. Define el circuito, no el número.",
        "An alert nobody receives is a log. It defines the process, not the number.",
        "Um alerta que não chega a ninguém é um log. Define o circuito, não o número."),
       ("Dueño del dato + TI", "Data owner + IT", "Dono do dado + TI"),
       ("¿Por qué canal: mail, Teams, un tablero que alguien mira?",
        "Through which channel: email, Teams, a dashboard someone watches?",
        "Por qual canal: e-mail, Teams, um painel que alguém olha?")),
    # ----------------------------------------------------------- 7 features
    _q("FEA-01", "features",
       ("¿Qué cálculos o indicadores arma hoy cada uno por su cuenta en su propia planilla?",
        "Which calculations or metrics does each person build on their own spreadsheet today?",
        "Quais cálculos ou indicadores cada um monta hoje por conta própria na sua planilha?"),
       ("Cada fórmula suelta es una versión distinta de la verdad. Centralizarlas es la mitad del proyecto.",
        "Every loose formula is a different version of the truth. Centralising them is half the project.",
        "Cada fórmula solta é uma versão diferente da verdade. Centralizá-las é metade do projeto."),
       ("Analistas de cada área", "Analysts in each area", "Analistas de cada área"),
       ("¿Podemos ver esa planilla? ¿La fórmula está escrita o es arrastrar celdas?",
        "Can we see that spreadsheet? Is the formula written down or is it dragging cells?",
        "Podemos ver essa planilha? A fórmula está escrita ou é arrastar células?")),
    # ---------------------------------------------------------------- 8 MDM
    _q("MDM-01", "mdm",
       ("¿Un mismo cliente/producto/proveedor puede estar cargado dos veces? ¿Cómo se dan cuenta?",
        "Can the same customer/product/supplier be loaded twice? How do you notice?",
        "Um mesmo cliente/produto/fornecedor pode estar cadastrado duas vezes? Como percebem?"),
       ("Es el defecto que más distorsiona los números del negocio, y el que más cuesta arreglar tarde.",
        "It is the defect that distorts business numbers the most, and the costliest to fix late.",
        "É o defeito que mais distorce os números do negócio, e o mais caro de arrumar tarde."),
       ("Responsable del maestro", "Master data owner", "Responsável pelo cadastro mestre"),
       ("¿Qué campo debería ser único: RUT, CUIT, mail, código interno?",
        "Which field should be unique: tax ID, email, internal code?",
        "Qual campo deveria ser único: CNPJ/CPF, e-mail, código interno?"),
       ("Cuando encuentran dos, ¿cuál gana? ¿Se fusionan o se marca uno de baja?",
        "When you find two, which one wins? Do you merge them or mark one inactive?",
        "Quando encontram dois, qual ganha? Fundem ou marcam um como inativo?")),
    _q("MDM-02", "mdm",
       ("¿Quién puede dar de alta un cliente o un producto nuevo, y con qué controles?",
        "Who can create a new customer or product, and with what controls?",
        "Quem pode cadastrar um cliente ou produto novo, e com que controles?"),
       ("Si puede cualquiera y sin control, el maestro se vuelve a ensuciar apenas se limpie.",
        "If anyone can, with no control, the master gets dirty again as soon as it is cleaned.",
        "Se qualquer um pode, sem controle, o cadastro suja de novo assim que for limpo."),
       ("Responsable del maestro", "Master data owner", "Responsável pelo cadastro mestre"),
       ("¿Hay un circuito de aprobación o se carga directo?",
        "Is there an approval workflow or is it entered directly?",
        "Há um circuito de aprovação ou é cadastrado direto?")),
    # ------------------------------------------------------------- 9 linaje
    _q("LIN-01", "linaje",
       ("Tomando el número más importante de su tablero: ¿de dónde sale, paso por paso?",
        "Taking the most important number on your dashboard: where does it come from, step by step?",
        "Pegando o número mais importante do seu painel: de onde vem, passo a passo?"),
       ("Es la pregunta que revienta el 'confiamos en el tablero'. Casi nunca hay alguien que la sepa entera.",
        "It is the question that breaks 'we trust the dashboard'. Almost nobody knows the whole answer.",
        "É a pergunta que estoura o 'confiamos no painel'. Quase ninguém sabe a resposta inteira."),
       ("Analista de BI + TI", "BI analyst + IT", "Analista de BI + TI"),
       ("¿Hay algún paso manual en el medio? ¿Quién lo hace y qué pasa si falta?",
        "Is there a manual step in between? Who does it and what happens if they are away?",
        "Há algum passo manual no meio? Quem faz e o que acontece se faltar?")),
    _q("LIN-02", "linaje",
       ("Si mañana se cambia un campo en el sistema de origen, ¿quién se entera y cómo?",
        "If a field changes in the source system tomorrow, who finds out and how?",
        "Se amanhã mudar um campo no sistema de origem, quem fica sabendo e como?"),
       ("Sin esto, un cambio silencioso en el ERP rompe tres tableros y se descubre en una reunión de directorio.",
        "Without this, a silent ERP change breaks three dashboards and is found in a board meeting.",
        "Sem isso, uma mudança silenciosa no ERP quebra três painéis e se descobre numa reunião de diretoria."),
       ("TI / responsable del ERP", "IT / ERP owner", "TI / responsável pelo ERP"),
       ("¿Ya pasó? ¿Cuánto tardaron en darse cuenta?",
        "Has it happened? How long did it take to notice?",
        "Já aconteceu? Quanto tempo levaram para perceber?")),
    # ---------------------------------------------------------- 10 glosario
    _q("GLO-01", "glosario",
       ("¿Qué quiere decir exactamente 'cliente activo' para ustedes? ¿Y para el área de al lado?",
        "What exactly does 'active customer' mean to you? And to the area next door?",
        "O que significa exatamente 'cliente ativo' para vocês? E para a área ao lado?"),
       ("El término más usado suele ser el peor definido, y encima nadie duda de él.",
        "The most used term is usually the worst defined, and nobody questions it.",
        "O termo mais usado costuma ser o pior definido, e ninguém o questiona."),
       ("Referentes de negocio", "Business representatives", "Referentes de negócio"),
       ("¿Esa definición está escrita en algún lado o es acuerdo tácito?",
        "Is that definition written anywhere or is it a tacit agreement?",
        "Essa definição está escrita em algum lugar ou é acordo tácito?")),
    _q("GLO-02", "glosario",
       ("¿Quién tendría la última palabra si dos áreas definen el mismo término distinto?",
        "Who would have the final word if two areas define the same term differently?",
        "Quem teria a última palavra se duas áreas definirem o mesmo termo de forma diferente?"),
       ("Sin árbitro definido, el glosario se discute para siempre y no se publica nunca.",
        "With no referee, the glossary is debated forever and never published.",
        "Sem árbitro definido, o glossário se discute para sempre e nunca é publicado."),
       ("Sponsor / comité de datos", "Sponsor / data committee", "Patrocinador / comitê de dados"),
       ("¿Existe un comité de datos o hay que crearlo?",
        "Is there a data committee or does one need to be created?",
        "Existe um comitê de dados ou é preciso criar um?")),
    # -------------------------------------------------------- 11 políticas
    _q("POL-01", "politicas",
       ("¿Quién puede ver cada dato hoy, y quién lo autorizó?",
        "Who can see each piece of data today, and who authorised it?",
        "Quem pode ver cada dado hoje, e quem autorizou?"),
       ("Es la primera pregunta de cualquier auditoría, y la que más veces no tiene respuesta escrita.",
        "It is the first question in any audit, and the one most often with no written answer.",
        "É a primeira pergunta de qualquer auditoria, e a que mais vezes não tem resposta escrita."),
       ("Seguridad de la información", "Information security", "Segurança da informação"),
       ("¿Se revisa cada tanto o se otorga y queda para siempre?",
        "Is it reviewed periodically or granted once and kept forever?",
        "É revisado periodicamente ou concedido e fica para sempre?"),
       ("¿Qué pasa con los accesos cuando alguien cambia de área o se va?",
        "What happens to access when someone changes area or leaves?",
        "O que acontece com os acessos quando alguém muda de área ou sai?")),
    _q("POL-02", "politicas",
       ("¿Hay una auditoría, certificación o regulación que tengan que cumplir con estos datos?",
        "Is there an audit, certification or regulation you must comply with for this data?",
        "Há auditoria, certificação ou regulação a cumprir com estes dados?"),
       ("Cambia las prioridades enteras: una fecha de auditoría es el plazo real del proyecto.",
        "It changes every priority: an audit date is the project's real deadline.",
        "Muda todas as prioridades: uma data de auditoria é o prazo real do projeto."),
       ("Compliance / legales", "Compliance / legal", "Compliance / jurídico"),
       ("¿Cuándo es la próxima? ¿Qué les observaron la vez pasada?",
        "When is the next one? What was flagged last time?",
        "Quando é a próxima? O que foi apontado da última vez?")),
    _q("POL-03", "politicas",
       ("¿Cuánto tiempo hay que conservar cada dato, y qué se hace después?",
        "How long must each piece of data be kept, and what happens afterwards?",
        "Por quanto tempo cada dado deve ser conservado, e o que se faz depois?"),
       ("Guardar todo para siempre es caro y, con datos personales, además puede ser ilegal.",
        "Keeping everything forever is expensive and, with personal data, can also be illegal.",
        "Guardar tudo para sempre é caro e, com dados pessoais, também pode ser ilegal."),
       ("Legales + TI", "Legal + IT", "Jurídico + TI"),
       ("¿Alguna vez se borró algo? ¿Hay un procedimiento escrito?",
        "Has anything ever been deleted? Is there a written procedure?",
        "Alguma vez algo foi apagado? Há um procedimento escrito?")),
    # ------------------------------------------------------- 12 publicación
    _q("PUB-01", "publicacion",
       ("¿En qué herramienta miran los datos hoy, y quién arma esos reportes?",
        "In which tool do you look at the data today, and who builds those reports?",
        "Em qual ferramenta olham os dados hoje, e quem monta esses relatórios?"),
       ("Define a dónde tiene que llegar el resultado. Un gobierno que no llega a la herramienta no se usa.",
        "It decides where the result must land. Governance that never reaches the tool is not used.",
        "Define aonde o resultado precisa chegar. Governança que não chega à ferramenta não é usada."),
       ("Responsable de BI", "BI lead", "Responsável de BI"),
       ("¿Cuántos reportes hay? ¿Cuántos se miran de verdad?",
        "How many reports are there? How many are actually looked at?",
        "Quantos relatórios existem? Quantos são realmente olhados?")),
    _q("PUB-02", "publicacion",
       ("¿Quién mira estos números para tomar qué decisión, y cada cuánto?",
        "Who looks at these numbers to make which decision, and how often?",
        "Quem olha estes números para tomar qual decisão, e com que frequência?"),
       ("Es lo que separa un tablero que se usa de uno que se hizo. Si no hay decisión atrás, no hay proyecto.",
        "It separates a dashboard that is used from one that was merely built. No decision behind it, no project.",
        "Separa um painel que se usa de um que só foi feito. Sem decisão atrás, não há projeto."),
       ("Gerencia / sponsor", "Management / sponsor", "Gerência / patrocinador"),
       ("Si el número estuviera mal, ¿qué decisión se tomaría mal? ¿Cuánto costaría?",
        "If the number were wrong, which decision would go wrong? What would it cost?",
        "Se o número estivesse errado, qual decisão sairia errada? Quanto custaria?")),
    _q("PUB-03", "publicacion",
       ("¿Qué pasa si un reporte muestra un número distinto al del sistema de origen?",
        "What happens if a report shows a different number from the source system?",
        "O que acontece se um relatório mostrar um número diferente do sistema de origem?"),
       ("La respuesta describe la confianza real que le tienen a los datos, que es el problema a resolver.",
        "The answer describes the real trust they place in the data, which is the problem to solve.",
        "A resposta descreve a confiança real que têm nos dados, que é o problema a resolver."),
       ("Usuarios de negocio", "Business users", "Usuários de negócio"),
       ("¿A quién le reclaman? ¿Cuánto tarda en resolverse?",
        "Who do they complain to? How long does it take to resolve?",
        "A quem reclamam? Quanto demora para resolver?")),
    _q("FEA-02", "features",
       ("¿Hay algún cálculo que hoy hace una persona a mano todos los meses?",
        "Is there a calculation someone does by hand every month today?",
        "Há algum cálculo que hoje uma pessoa faz à mão todo mês?"),
       ("Es la automatización con retorno más fácil de justificar, y la que más rápido se nota.",
        "It is the easiest automation to justify, and the one that shows results fastest.",
        "É a automação mais fácil de justificar, e a que mostra resultado mais rápido."),
       ("Analista del área", "Area analyst", "Analista da área"),
       ("¿Cuántas horas por mes le lleva? ¿Qué pasa si esa persona está de licencia?",
        "How many hours a month does it take? What happens if that person is on leave?",
        "Quantas horas por mês leva? O que acontece se essa pessoa estiver de licença?")),
    _q("FEA-03", "features",
       ("¿Qué información les gustaría tener y hoy no existe en ningún sistema?",
        "What information would you like to have that today exists in no system?",
        "Que informação gostariam de ter e hoje não existe em nenhum sistema?"),
       ("Separa lo que hay que calcular de lo que hay que empezar a registrar. Son dos proyectos distintos.",
        "It separates what must be calculated from what must start being recorded. Two different projects.",
        "Separa o que precisa ser calculado do que precisa começar a ser registrado. Dois projetos distintos."),
       ("Gerencia del área", "Area management", "Gerência da área"),
       ("¿Se podría deducir de lo que ya se guarda, o habría que empezar a cargarlo?",
        "Could it be derived from what is already stored, or would it have to start being captured?",
        "Poderia ser deduzido do que já é guardado, ou teria que começar a ser registrado?")),
    _q("DIC-03", "diccionario",
       ("¿Hay un diccionario de datos escrito? ¿Quién lo mantiene y cuándo se actualizó por última vez?",
        "Is there a written data dictionary? Who maintains it and when was it last updated?",
        "Existe um dicionário de dados escrito? Quem o mantém e quando foi atualizado?"),
       ("Un diccionario desactualizado es peor que ninguno: se le cree, y manda a la gente al campo equivocado.",
        "An outdated dictionary is worse than none: people trust it and it sends them to the wrong field.",
        "Um dicionário desatualizado é pior que nenhum: acreditam nele e ele manda para o campo errado."),
       ("Arquitectura de datos / BI", "Data architecture / BI", "Arquitetura de dados / BI"),
       ("¿Lo usa alguien además de quien lo escribió?",
        "Does anyone besides its author use it?",
        "Alguém além de quem o escreveu o usa?")),
    _q("IDX-03", "indice",
       ("¿Qué nivel de error están dispuestos a tolerar antes de frenar un proceso?",
        "What level of error are you willing to tolerate before stopping a process?",
        "Que nível de erro estão dispostos a tolerar antes de parar um processo?"),
       ("Sin umbral acordado, cada alerta se discute de nuevo y al mes nadie las mira.",
        "With no agreed threshold, every alert is re-argued and within a month nobody looks at them.",
        "Sem limite acordado, cada alerta é rediscutido e em um mês ninguém olha mais."),
       ("Dueño del dato + operaciones", "Data owner + operations", "Dono do dado + operações"),
       ("¿Ese umbral es el mismo para todos los datos o hay alguno crítico?",
        "Is that threshold the same for all data or is some of it critical?",
        "Esse limite é o mesmo para todos os dados ou há algum crítico?")),
    _q("MDM-03", "mdm",
       ("¿Los códigos de cliente/producto significan algo, o son un número corrido?",
        "Do customer/product codes mean something, or are they just a running number?",
        "Os códigos de cliente/produto significam algo, ou são um número sequencial?"),
       ("Un código con significado adentro se rompe el día que el significado cambia, y ese día llega.",
        "A code with meaning baked in breaks the day the meaning changes, and that day comes.",
        "Um código com significado embutido quebra no dia em que o significado muda, e esse dia chega."),
       ("Responsable del maestro", "Master data owner", "Responsável pelo cadastro mestre"),
       ("¿Se reutilizan códigos de registros dados de baja?",
        "Are codes from deactivated records reused?",
        "Códigos de registros inativados são reutilizados?")),
    _q("LIN-03", "linaje",
       ("¿Hay procesos que corren en la máquina de alguien y no en un servidor?",
        "Are there processes running on someone's machine rather than a server?",
        "Há processos que rodam na máquina de alguém e não em um servidor?"),
       ("Es el punto único de falla más común y el que menos figura en ningún diagrama.",
        "It is the most common single point of failure and the least likely to appear in any diagram.",
        "É o ponto único de falha mais comum e o que menos aparece em qualquer diagrama."),
       ("TI / analistas", "IT / analysts", "TI / analistas"),
       ("¿Alguien más sabe correrlo? ¿Está el código guardado en algún lado?",
        "Does anyone else know how to run it? Is the code stored anywhere?",
        "Mais alguém sabe rodá-lo? O código está guardado em algum lugar?")),
    _q("GLO-03", "glosario",
       ("¿Qué palabra usan ustedes que en otra empresa del rubro significa otra cosa?",
        "Which word do you use that means something else at another company in your industry?",
        "Que palavra vocês usam que em outra empresa do setor significa outra coisa?"),
       ("Marca dónde el consultor va a asumir mal por venir de otro cliente. Es prevención barata.",
        "It flags where the consultant will assume wrong from a previous client. Cheap prevention.",
        "Marca onde o consultor vai supor errado por vir de outro cliente. Prevenção barata."),
       ("Referentes de negocio", "Business representatives", "Referentes de negócio"),
       ("¿Cómo lo llamarían si tuvieran que explicárselo a alguien de afuera?",
        "What would you call it if you had to explain it to an outsider?",
        "Como chamariam isso se tivessem que explicar para alguém de fora?")),
    # ------------------------------------------------ transversales (alcance)
    _q("GEN-01", "ingesta",
       ("Si esto sale bien, ¿qué van a poder hacer dentro de seis meses que hoy no pueden?",
        "If this goes well, what will you be able to do in six months that you cannot today?",
        "Se isso der certo, o que vão poder fazer em seis meses que hoje não podem?"),
       ("Es el criterio de éxito dicho por el cliente. Sin él, el éxito lo define el que factura.",
        "It is the success criterion in the client's own words. Without it, whoever invoices defines success.",
        "É o critério de sucesso nas palavras do cliente. Sem ele, quem fatura define o sucesso."),
       ("Sponsor del proyecto", "Project sponsor", "Patrocinador do projeto"),
       ("¿Cómo lo mediríamos? ¿Quién firma que se cumplió?",
        "How would we measure it? Who signs off that it was met?",
        "Como mediríamos? Quem assina que foi cumprido?")),
    _q("GEN-02", "catalogo",
       ("¿Quién dentro de la empresa va a poder dedicarle horas a esto, y cuántas por semana?",
        "Who inside the company will be able to spend hours on this, and how many per week?",
        "Quem dentro da empresa vai poder dedicar horas a isso, e quantas por semana?"),
       ("Un proyecto de gobierno sin horas del cliente no se hace: la mitad del trabajo es decidir, y eso no se terceriza.",
        "A governance project without client hours does not happen: half the work is deciding, and that cannot be outsourced.",
        "Um projeto de governança sem horas do cliente não acontece: metade do trabalho é decidir, e isso não se terceiriza."),
       ("Sponsor del proyecto", "Project sponsor", "Patrocinador do projeto"),
       ("¿Esa persona ya tiene otras prioridades asignadas para el mismo período?",
        "Does that person already have other priorities assigned for the same period?",
        "Essa pessoa já tem outras prioridades atribuídas para o mesmo período?")),
]
